### ISSUE TITLE
```devc build``` don't work with config ```dockerFile``` in stead of ```build.dockerFile```

### ISSUE THREAD

**Issue by europrimus** [nikaro/devc#15]
Hi,
Thanks for making this software.

I try to setup a dev container for [home assistant](https://github.com/home-assistant/core)
First I have a config file error because of a line of comment in json, I know this it not permitted in json standard.
After removing this line, I have this error
```
 panic: cannot determine which command to use

goroutine 1 [running]:
git.sr.ht/~nka/devc/cmd.preRun(0x9a8000, 0x9df4c0, 0x0, 0x0)
	/home/runner/work/devc/devc/cmd/root.go:55 +0x32c
github.com/spf13/cobra.(*Command).execute(0x9a8000, 0x9df4c0, 0x0, 0x0, 0x9a8000, 0x9df4c0)
	/home/runner/work/devc/devc/vendor/github.com/spf13/cobra/command.go:843 +0x231
github.com/spf13/cobra.(*Command).ExecuteC(0x9a87e0, 0x9b1b80, 0x0, 0xc000042778)
	/home/runner/work/devc/devc/vendor/github.com/spf13/cobra/command.go:977 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/work/devc/devc/vendor/github.com/spf13/cobra/command.go:905
git.sr.ht/~nka/devc/cmd.Execute()
	/home/runner/work/devc/devc/cmd/root.go:28 +0x31
main.main()
	/home/runner/work/devc/devc/main.go:6 +0x25
```

In the [config file](https://github.com/home-assistant/core/blob/3896b4a31d993587aeb432a16f0b8627217ccb44/.devcontainer/devcontainer.json#L3-L4) ```context``` and ```dockerFile``` properties are at root, not under the ```build``` section.
After editing the config file like under, it start building docker image.
```diff
diff --git a/.devcontainer/devcontainer.json b/.devcontainer/devcontainer.json
index 2f94441940..4bf695b90d 100644
--- a/.devcontainer/devcontainer.json
+++ b/.devcontainer/devcontainer.json
@@ -1,7 +1,9 @@
 {
   "name": "Home Assistant Dev",
-  "context": "..",
-  "dockerFile": "../Dockerfile.dev",
+  "build":{
+    "context": "..",
+    "dockerFile": "../Dockerfile.dev"
+  },
   "postCreateCommand": "script/setup",
   "postStartCommand": "script/bootstrap",
   "containerEnv": { "DEVCONTAINER": "1" },
@@ -13,7 +15,6 @@
     "redhat.vscode-yaml",
     "esbenp.prettier-vscode"
   ],
-  // Please keep this file in sync with settings in home-assistant/.vscode/settings.default.json
   "settings": {
     "python.pythonPath": "/usr/local/bin/python",
     "python.linting.pylintEnabled": true,
```

In the [devcontainer.json reference](https://github.com/Microsoft/vscode-docs/blob/master/docs/remote/devcontainerjson-reference.md) the two places are allowed 
>```build.dockerfile``` / ```dockerFile```
>```build.context``` / ```context```

This is not a high priority, i can keep my patched version of ```devcontainer.json```, but, I think,  it's a good to be fully compatible with **vscode**.

**Comment by nikaro** [comment]
Thanks to @linquize it seems to be fixed, however there is another problem with the home assistant devcontainer file, it contains a comment. Something to VSCode support, but which is not strictly valid JSON, thus unsupported by viper.

As suggested in https://github.com/spf13/viper/issues/90 it tried to replace `SetConfigType` with HCL or YAML as the are supposed to support JSON with comments, but neither seem to work.

**Comment by nikaro** [comment]
Sadly i don't think we can fix this issue (JSON comments) without replacing the library used to read the devcontainer file. Something i'm not willing to do, at least for now.
