### ISSUE TITLE
Unable to install on Arch

### ISSUE THREAD

**Issue by Joachim-42he** [nikaro/devc#22]
### Repository URL

https://github.com/nikaro/devc

### Debug output

```Shell
Install from github:

> git clone https://github.com/nikaro/devc                                                             
Klone nach 'devc'...
remote: Enumerating objects: 2465, done.
remote: Counting objects: 100% (237/237), done.
remote: Compressing objects: 100% (167/167), done.
remote: Total 2465 (delta 140), reused 72 (delta 66), pack-reused 2228
Empfange Objekte: 100% (2465/2465), 3.26 MiB | 9.35 MiB/s, fertig.
Löse Unterschiede auf: 100% (1461/1461), fertig.
> cd devc                                                                                             
> make                                                                                              
Building...
env CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -mod vendor -ldflags="-s -w -X 'main.version=v1.0.0-beta.6-4-gd9181f1'" -o build/devc-linux-amd64 .
go build: when using gccgo toolchain, please pass linker flags using -gccgoflags, not -ldflags
# golang.org/x/exp/constraints
vendor/golang.org/x/exp/constraints/constraints.go:13:9: Fehler: invalid character 0x7e in input file
   13 |         ~int | ~int8 | ~int16 | ~int32 | ~int64
      |         ^
vendor/golang.org/x/exp/constraints/constraints.go:20:9: Fehler: invalid character 0x7e in input file
   20 |         ~uint | ~uint8 | ~uint16 | ~uint32 | ~uint64 | ~uintptr
      |         ^
vendor/golang.org/x/exp/constraints/constraints.go:27:9: Fehler: expected signature or type name
   27 |         Signed | Unsigned
      |         ^
vendor/golang.org/x/exp/constraints/constraints.go:34:9: Fehler: invalid character 0x7e in input file
   34 |         ~float32 | ~float64
      |         ^
vendor/golang.org/x/exp/constraints/constraints.go:41:9: Fehler: invalid character 0x7e in input file
   41 |         ~complex64 | ~complex128
      |         ^
vendor/golang.org/x/exp/constraints/constraints.go:49:9: Fehler: expected signature or type name
   49 |         Integer | Float | ~string
      |         ^
vendor/golang.org/x/exp/constraints/constraints.go:49:27: Fehler: invalid character 0x7e in input file
   49 |         Integer | Float | ~string
      |                           ^
make: *** [Makefile:26: build] Fehler 2

Install using `go install`:
```
> go install github.com/nikaro/devc@latest                                                        
go: github.com/nikaro/devc@latest: github.com/nikaro/devc@v0.4.1: parsing go.mod:
	module declares its path as: git.karolak.fr/nicolas/devc
	       but was required as: github.com/nikaro/devc
```
Trying to Install `devc`.package from AUR:
```
/home/joachim/.cache/yay/devc/PKGBUILD: Zeile 24: cd: /home/joachim/.cache/yay/devc/src/devc-v1.0.0-alpha.4: Datei oder Verzeichnis nicht gefunden
```
Trying to Install `devc-bin`.package from AUR:
```
install: der Aufruf von stat für './man/devc*.1' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
```
```

### What OS are you seeing the problem on?

Linux

### Details

I seem to have a bit of tough luck trying to install `devc` on EndeavourOS (Arch). 
1. Trying to build from source fails with errors about invalid characters.
2. Trying to install via Go with the `latest` tag tries to install 0.41 (?) and fails because of a wrong path declaration.
3. Trying to install the `devc`-package from AUR fails because of a naming error in the `tar.gz` (folder is named `devc-1.0.0-alpha.4` instead of `devc-v1.0.0-alpha.4`).
4. Trying to install the `devc-bin`-package from AUR fails because of misseng files `./man/devc*.1`.

**Comment by Joachim-42he** [comment]
I just tried installing via `go install github.com/nikaro/devc@v1.0.0-beta.6` which also failed because of invalid characters and other errors like the install from source above.

**Comment by nikaro** [comment]
For the "invalid character" i do not reproduce it on my ArchLinux:

```
nicolas@archlinux ~/g/s/g/n/devc (main)> make
Building...
env CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -mod vendor -ldflags="-s -w -X 'main.version=v1.0.0-beta.6-4-gd9181f1'" -o build/devc-linux-amd64 .
nicolas@archlinux ~/g/s/g/n/devc (main)>
```

```
nicolas@archlinux ~ > go install github.com/nikaro/devc@v1.0.0-beta.6
go: downloading github.com/nikaro/devc v1.0.0-beta.6
go: downloading github.com/rs/zerolog v1.28.0
go: downloading github.com/samber/lo v1.28.2
go: downloading github.com/spf13/afero v1.9.2
go: downloading github.com/spf13/cobra v1.5.0
go: downloading muzzammil.xyz/jsonc v1.0.0
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.2
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading github.com/mattn/go-colorable v0.1.13
go: downloading golang.org/x/exp v0.0.0-20220916125017-b168a2c6b86b
go: downloading github.com/russross/blackfriday/v2 v2.1.0
go: downloading github.com/mattn/go-isatty v0.0.16
go: downloading golang.org/x/sys v0.0.0-20220915200043-7b5979e65e41
nicolas@archlinux ~>
```

May be take a look at your Go version and your locale:
```
nicolas@archlinux ~> go version
go version go1.19.2 linux/amd64
nicolas@archlinux ~> echo $LANG
en_US.UTF-8
```

This said, it occurs within this package `https://pkg.go.dev/golang.org/x/exp/constraints`, so if it persists it should be reported up there. Check out https://cs.opensource.google/go/x/exp/+/master:CONTRIBUTING.md.

The AUR packages errors are on my side, for instance the `devc` has been a bit left aside for a while now since i'm trying to automate the release workflow, and only `devc-bin` is included in this workflow for now.

I'm currently looking at what is the issue with `devc-bin`.

**Comment by nikaro** [comment]
@Joachim-42he the `devc-bin` AUR package is fixed, but goreleaser does not handle correctly the "beta" part of the version so you may need to cleanup your yay cache.

I will try to fix the `devc` one, and may be add a `devc-git`.

**Comment by nikaro** [comment]
`devc` fixed and updated, but you will be better served by `devc-bin` since you have build issues.

(Let me know if there are any progress on the build and feel free to ask questions)

**Comment by Joachim-42he** [comment]
Thank you. After cleaning my caches, devc-bin installed correctly. :+1:

**Comment by Joachim-42he** [comment]
Just as feedback for future reporters, my problem with `go install github.com/nikaro/devc@latest` and ` invalid characters` under Arch Linux was that I had the package `go-gcc` installed instead of the `go` package.
