### ISSUE TITLE
Handle `dockerComposeFile` like vscode

### ISSUE THREAD

**Issue by Joachim-42he** [nikaro/devc#27]
### Request

I would like to be able to use the same devcontainer.json for vscode and devc. In the [official reference](https://containers.dev/implementors/json_reference/), `dockerComposeFile` is either a string or an array. Devc only allows for it to be a string.  
Also. in the case of it being an empty array, vscode excutes `docker compose up -d` in the project's root directory, thus using both the docker-compose.yml **and** docker-compose.override.yml. This is especially useful in shared projects.

**Comment by nikaro** [comment]
> In the [official reference](https://containers.dev/implementors/json_reference/), dockerComposeFile is either a string or an array. Devc only allows for it to be a string.

Yeah i'm aware of that, since Golang strict typing system does not allow to say `this` could be an array or a string i had to make a choice. And i never used the array syntax 🤷 

But it seems that the array allow for more flexible usages, like yours. I will change it to use array.

But i don't have enough mastery of Go for allowing both types.

> Also. in the case of it being an empty array, vscode excutes docker compose up -d in the project's root directory, thus using both the docker-compose.yml and docker-compose.override.yml. This is especially useful in shared projects.

I will see if i can implement this by the way.

**Comment by Joachim-42he** [comment]
I am a complete Go beginner myself otherwise I would gladly provide a PR for you. I imagine to enable both string and array values, you would need to use an interface and test or map to a type. Being able to do that would be helpful anyway, because there are multiple values in the devcontainer.jon-reference that can be one of multiple data types that you might want to support in the future.

**Comment by nikaro** [comment]
I'll probably go for https://github.com/spf13/viper for reading `devcontainer.json`, it should simplify a bit the code and allow for more flexibility. But it will need to rewrite many things i think.
